### ISSUE TITLE
Regression in libclang@1.0.0-beta.4

### ISSUE THREAD

**Issue by shirakaba** [aapoalas/libclang-deno#2]
On macOS M1 on Deno v1.30.0 (latest stable):

```ts
// index.ts
const index = new CXIndex(false);
```

```sh
# Run the script using Clang 14.0.0 (which comes with Xcode)
LIBCLANG_PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib deno run --unstable --allow-env=LIBCLANG_PATH --allow-ffi index.ts
```

This gives the following error on `libclang@1.0.0-beta.4` which was not present in `libclang@1.0.0-beta.3`:

```
error: Uncaught TypeError: Cannot read properties of undefined (reading 'symbols')
    this.#pointer = libclang.symbols.clang_createIndex(
                             ^
    at new CXIndex (https://deno.land/x/libclang@1.0.0-beta.4/mod.ts:281:30)
    at generateFrameworkMetadata (file:///Users/jamie/Documents/git/clang_metagen_deno/src/gen.ts:150:17)
    at file:///Users/jamie/Documents/git/clang_metagen_deno/src/index.ts:3:16
```

**Comment by aapoalas** [comment]
Thank you for the report! I had indeed messed up the logic for opening libclang when a directory path is given. This is now fixed and a new ~~beta.5~~ beta.6 is released.

Fixed in: https://github.com/aapoalas/libclang_deno/commit/771cd0be5f8d5653e326f2308b9d8e2339a2cbd3
